### PR TITLE
Improve Shakespeare -> S-Lang and vendor Makefile

### PR DESCRIPTION
**Pull request by e666666**
I'm trying to run the program on an LFS system(Yep), and I had some issues. One with the Shakespeare language and another with vendor building. And so, in case that the fixes are useful for more than just my specific case, I'm putting this PR request here.
Please tell me what you think about it.

### CODE REVIEW

**Comment by mame** [comment]
Thanks!

**Comment by mame** [comment]
@e666666 `-z muldefs` looks a better solution. Does it work for you too? If so I'll rewrite it.

**Comment by e666666** [comment]
@mame That works for me as well! And in case you wonder, I'm at language 20 right now, still installing commands as they are found missing.

**Comment by mame** [comment]
Thanks! I have changed it at deddbd7c0452b2e99da78000de03197c5cadc76f

**Pull request merged**
