### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by MakeNowJust**
```console
$ sudo docker build -t quine-relay .
$ sudo docker run -t quine-relay
```

### CODE REVIEW

**Comment by mame** [comment]
Thank you, that's what I've wanted to do.  I'll try and merge yout patch later.
I think PPAs are not needed because Ubuntu 14.10 provides the packages officially.

**Comment by MakeNowJust** [comment]
I see. Even if I remove PPAs from Dockerfile, `docker build` and `docker run` is successful.

By the way, if you want to push this Docker image, please you to append MAINTAINER instruction into Dockerfile.

**Comment by dsoprea** [comment]
This is a fantastic idea. Thanks for contributing this.


On Tue, Feb 24, 2015 at 7:03 PM, TSUYUSATO Kitsune <notifications@github.com

**Comment by mame** [comment]
Sorry for the late action.  Merged, thank you.
But I think it is hard to me to maintain Dockerfile, so please help me if I get a bug report about it ;-)

**Pull request merged**
